#!/bin/bash
# ~/.local/bin/fortran_project.sh


bold=$(tput bold)
normal=$(tput sgr0)

WORK_DIR="${FORTRAN_PROJECTS:-$HOME/codes}"

[ -d "$WORK_DIR" ] || mkdir -p "$WORK_DIR"

write_ford_file() {
echo " ---
project: $1
summary: <a summary of what this is>
project_github: <link_to_your_projects_github>
author: <you>
author_description: <a description of you>
email: <email>
github: <link_to_your_github>
src_dir: src
exclude_dir: test doc
output_dir: doc/ford_site
preprocessor: gfortran -E
display: public
         protected
         private
source: false
proc_internals: true
sort: permission-alpha
docmark_alt: !>
docmark: !
predocmark_alt: *
print_creation_date: true
creation_date: %Y-%m-%d %H:%M %z
md_extensions: markdown.extensions.toc
               markdown.extensions.smarty
graph: false
license: MIT
page_dir: doc/page
media_dir: doc/media
---

[TOC]

{!README.md!}
" > ford.md
}


h="fortran_project <new|list|work|update>

Manage your Fortran based projects locally with fpm and vscode.

USAGE:
    - fortran_project ${bold}new${normal} <project_name>
        Create a new project.
        The default folder will be at ~/codes, but it can be set up with
        the environment variable FORTRAN_PROJECTS.
        If the directory doesn't exist, it will be created.

    - fortran_project ${bold}list${normal}
        List all the existing Fortran projects.
    
    - fortran_project ${bold}work${normal}
        Open vscode on the selected project directory.

    - fortran_project ${bold}update${normal}
        Update the fortran_project script
"

case $1 in
    "new")
        if [ -z "$2" ]; then
            echo "ERROR!"
            echo "Project name must be provided!"
            exit 1
        fi

        cd "$WORK_DIR"

        nombre="$2"
        fpm new "$nombre" &&

        cd "$nombre" &&
        # Añade configuraciones generales de vscode al proyecto
        git submodule add "https://github.com/ipqa-research/vscode-fortran.git" .vscode

        write_ford_file "$nombre"
        ;;
    "list")
        ls $WORK_DIR;;
    "work")
        proj="$(ls $WORK_DIR | fzf)"
        cd "$WORK_DIR/$proj"
        [ "$proj" = "" ] || code "$WORK_DIR/$proj"
        ;;
    "update")
        script="$(curl https://raw.githubusercontent.com/ipqa-research/fortran-setup/main/fortran_project)"
        echo "$script" > ~/.local/bin/fortran_project
        chmod +x ~/.local/bin/fortran_project
        ;;
    "docs")
        ford docs.md
        ;;
    *)
        echo "$h"
        ;;
esac
