#!/bin/bash
# ~/.local/bin/fortran_project.sh


bold=$(tput bold)
normal=$(tput sgr0)

WORK_DIR="${FORTRAN_PROJECTS:-$HOME/codes}"

[ -d "$WORK_DIR" ] || mkdir -p "$WORK_DIR"

h="fortran_project <new|list|work>

Manage your Fortran based projects locally with fpm and vscode.

USAGE:
    - fortran_project ${bold}new${normal} <project_name>
        Create a new project.
        The default folder will be at ~/codes, but it can be set up with
        the environment variable FORTRAN_PROJECTS.
        If the directory doesn't exist, it will be created.

    - fortran_project ${bold}list${normal}
        List all the existing Fortran projects.
    
    - fortran_project ${bold}work${normal}
        Open vscode on the selected project directory.

    - fortran_project ${bold}update${normal}
        Update the fortran_project script
"

case $1 in
    "new")
        if [ -z "$2" ]; then
            echo "ERROR!"
            echo "Project name must be provided!"
            exit 1
        fi

        cd "$WORK_DIR"

        nombre="$2"
        fpm new "$nombre" &&

        cd "$nombre" &&
        # Añade configuraciones generales de vscode al proyecto
        git submodule add "https://github.com/ipqa-research/vscode-fortran.git" .vscode
        ;;
    "list")
        ls $WORK_DIR;;
    "work")
        proj="$(ls $WORK_DIR | fzf)"
        cd "$WORK_DIR/$proj"
        [ "$proj" = "" ] || code "$WORK_DIR/$proj"
        ;;
    "update")
        script="$(curl https://raw.githubusercontent.com/ipqa-research/fortran-setup/main/fortran_project)"
        echo "$script" > ~/.local/bin/fortran_project
        chmod +x ~/.local/bin/fortran_project
        ;;
    *)
        echo "$h"
        ;;
esac
